/**
 * @file levels.js
 * @description Defines the grid levels (start position, exit, walls) for the "Escape the Loop" game mode.
 */

const levels = [
    {
        id: 1,
        cols: 6,
        rows: 6,
        start: { x: 0, y: 5, dir: "up" },
        exit: { x: 5, y: 1 },
        walls: [
            { x: 1, y: 5 },
            { x: 1, y: 4 },
            { x: 1, y: 3 },
            { x: 2, y: 3 },
            { x: 3, y: 3 },
            { x: 3, y: 2 },
            { x: 3, y: 1 },
            { x: 4, y: 1 },
        ],
    },
    {
        id: 2,
        cols: 5,
        rows: 5,
        start: { x: 4, y: 4, dir: "left" },
        exit: { x: 0, y: 0 },
        walls: [
            { x: 1, y: 4 },
            { x: 1, y: 3 },
            { x: 1, y: 2 },
            { x: 2, y: 2 },
            { x: 3, y: 2 },
            { x: 3, y: 1 },
        ],
    },
    {
        id: 3,
        cols: 7,
        rows: 5,
        start: { x: 0, y: 2, dir: "right" },
        exit: { x: 6, y: 2 },
        walls: [
            { x: 2, y: 0 },
            { x: 2, y: 1 },
            { x: 2, y: 3 },
            { x: 2, y: 4 },
            { x: 4, y: 0 },
            { x: 4, y: 2 },
            { x: 4, y: 3 },
            { x: 4, y: 4 },
        ],
    },
    {
        id: 4, // Long Corridor - perfect for loop
        cols: 8,
        rows: 3,
        start: { x: 0, y: 1, dir: "right" },
        exit: { x: 7, y: 1 },
        walls: [],
    },
    {
        id: 5, // Snake
        cols: 6,
        rows: 6,
        start: { x: 0, y: 0, dir: "down" },
        exit: { x: 5, y: 5 },
        walls: [
            { x: 1, y: 0 },
            { x: 1, y: 1 },
            { x: 1, y: 2 },
            { x: 1, y: 3 },
            { x: 1, y: 4 },
            { x: 3, y: 1 },
            { x: 3, y: 2 },
            { x: 3, y: 3 },
            { x: 3, y: 4 },
            { x: 3, y: 5 },
        ],
    },
    {
        id: 6, // Stairs
        cols: 7,
        rows: 7,
        start: { x: 0, y: 6, dir: "right" },
        exit: { x: 6, y: 0 },
        walls: [
            { x: 1, y: 6 },
            { x: 1, y: 5 },
            { x: 1, y: 4 },
            { x: 2, y: 4 },
            { x: 3, y: 4 },
            { x: 3, y: 3 },
            { x: 3, y: 2 },
            { x: 4, y: 2 },
            { x: 5, y: 2 },
            { x: 5, y: 1 },
            { x: 5, y: 0 },
        ],
    },
    {
        id: 7, // Spiral
        cols: 7,
        rows: 7,
        start: { x: 0, y: 0, dir: "right" },
        exit: { x: 3, y: 3 },
        walls: [
            { x: 1, y: 1 },
            { x: 2, y: 1 },
            { x: 3, y: 1 },
            { x: 4, y: 1 },
            { x: 5, y: 1 },
            { x: 5, y: 2 },
            { x: 5, y: 3 },
            { x: 5, y: 4 },
            { x: 5, y: 5 },
            { x: 4, y: 5 },
            { x: 3, y: 5 },
            { x: 2, y: 5 },
            { x: 1, y: 5 },
            { x: 1, y: 4 },
            { x: 1, y: 3 },
            { x: 2, y: 3 },
        ],
    },
    {
        id: 8, // Zig Zag
        cols: 8,
        rows: 6,
        start: { x: 0, y: 5, dir: "right" },
        exit: { x: 7, y: 0 },
        walls: [
            { x: 2, y: 5 },
            { x: 2, y: 4 },
            { x: 2, y: 3 },
            { x: 2, y: 2 },
            { x: 2, y: 1 },
            { x: 4, y: 4 },
            { x: 4, y: 3 },
            { x: 4, y: 2 },
            { x: 4, y: 1 },
            { x: 4, y: 0 },
            { x: 6, y: 5 },
            { x: 6, y: 4 },
            { x: 6, y: 3 },
            { x: 6, y: 2 },
            { x: 6, y: 1 },
        ],
    },
    {
        id: 9, // Blocked paths
        cols: 9,
        rows: 5,
        start: { x: 0, y: 2, dir: "right" },
        exit: { x: 8, y: 2 },
        walls: [
            { x: 2, y: 2 },
            { x: 4, y: 2 },
            { x: 6, y: 2 },
            { x: 1, y: 0 },
            { x: 3, y: 4 },
            { x: 5, y: 0 },
            { x: 7, y: 4 },
        ],
    },
    {
        id: 10, // The Grand Factory
        cols: 10,
        rows: 10,
        start: { x: 0, y: 9, dir: "up" },
        exit: { x: 9, y: 0 },
        walls: [
            { x: 0, y: 8 },
            { x: 1, y: 8 },
            { x: 2, y: 8 },
            { x: 3, y: 8 },
            { x: 4, y: 8 },
            { x: 4, y: 9 },
            { x: 6, y: 9 },
            { x: 6, y: 8 },
            { x: 6, y: 7 },
            { x: 6, y: 6 },
            { x: 7, y: 6 },
            { x: 8, y: 6 },
            { x: 8, y: 5 },
            { x: 8, y: 4 },
            { x: 8, y: 3 },
            { x: 7, y: 3 },
            { x: 6, y: 3 },
            { x: 5, y: 3 },
            { x: 4, y: 3 },
            { x: 3, y: 3 },
            { x: 2, y: 5 },
            { x: 2, y: 6 },
            { x: 1, y: 5 },
            { x: 1, y: 4 },
            { x: 1, y: 3 },
        ],
    },
];

if (typeof module !== "undefined" && module.exports) {
    module.exports = levels;
} else if (typeof window !== "undefined") {
    window.levels = levels;
}
